import os
import json
import yaml
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, Callable, Dict, List, Any
import click

@dataclass
class AgentIntegration:
    name: str           # display name e.g. "Claude Code"
    slug: str           # CLI slug e.g. "claude-code"
    phase: int          # 1, 2, or 3
    config_paths: list[str]   # relative paths this agent writes
    env_vars: Dict[str, str] = field(default_factory=dict)  # env var name → description
    skill_path: Optional[str] = None # for Phase 2 skill-file agents
    setup_fn: Optional[Callable] = None # _setup_<slug>(project_dir, nb_url, api_key, global_dir, dry_run, force) -> list[Path]
    launch_cmd: Optional[str] = None # CLI command to launch this agent
    launch_env_vars: Dict[str, str] = field(default_factory=dict) # env var name -> value (can use {nb_url}, {api_key})

def _nb_url(config=None) -> str:
    """Reads server.host/server.port from loaded config, falls back to http://localhost:8000"""
    if config and config.server:
        host = config.server.host
        if host == "0.0.0.0":
            host = "localhost"
        return f"http://{host}:{config.server.port}"
    return "http://localhost:8000"

def _api_key() -> str:
    """Reads NB_API_KEY env var, falls back to 'nb-local'"""
    return os.environ.get("NB_API_KEY", "nb-local")

def _write_json(path: Path, data: Dict[str, Any], dry_run: bool, force: bool) -> Path:
    """Writes JSON with '_neuralbroker': 'auto-generated' field."""
    data["_neuralbroker"] = "auto-generated"
    if dry_run:
        click.echo(f"[DRY-RUN] Would write JSON to {path}")
        return path
    
    if path.exists() and not force:
        if not click.confirm(f"File {path} already exists. Overwrite?", default=False):
            return path
            
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    return path

def _write_text(path: Path, content: str, dry_run: bool, force: bool) -> Path:
    """Writes text with comment header."""
    header = "# Generated by NeuralBroker — edit manually or re-run: neuralbrok integrations setup\n"
    if path.suffix == ".md":
        header = "<!-- Generated by NeuralBroker — edit manually or re-run: neuralbrok integrations setup -->\n"
    
    full_content = header + content
    
    if dry_run:
        click.echo(f"[DRY-RUN] Would write to {path}")
        return path
        
    if path.exists() and not force:
        if not click.confirm(f"File {path} already exists. Overwrite?", default=False):
            return path
            
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(full_content, encoding="utf-8")
    return path

def _skill_file_content(agent_name: str, env_var: str) -> str:
    """Generates markdown skill file template."""
    return f"""# NeuralBroker Skill for {agent_name}

This skill configures {agent_name} to use NeuralBroker as its primary inference engine.

## Configuration
- **API URL:** http://localhost:8000
- **Model:** Any OpenAI-compatible model (e.g., gpt-4o, claude-3-5-sonnet)
- **API Key:** Linked to your `{env_var}` environment variable.

## Instructions
When this skill is active, routing is handled automatically by NeuralBroker:
- High VRAM availability: Routes to local Ollama.
- Low VRAM availability: Routes to configured cloud providers (Groq, Together, etc.).
"""

# --- Phase 1 Setup Functions ---

def _setup_claude_code(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    settings_path = base / ".claude" / "settings.json"
    claude_md_path = base / "CLAUDE.md"
    
    settings = {
        "api_endpoint": f"{nb_url}/v1",
        "api_key": api_key,
        "model": "claude-3-5-sonnet-20240620"
    }
    
    paths = []
    paths.append(_write_json(settings_path, settings, dry_run, force))
    
    md_content = f"NeuralBroker integrated. Run `neuralbrok code` to see routing status.\n"
    paths.append(_write_text(claude_md_path, md_content, dry_run, force))
    
    return paths

def _setup_cursor(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    # Cursor uses MCP or direct OpenAI compat
    base = Path.home() if global_dir else project_dir
    mcp_path = base / ".cursor" / "mcp.json"
    env_path = project_dir / ".env"
    
    mcp_config = {
        "mcpServers": {
            "neuralbroker": {
                "command": "neuralbrok",
                "args": ["mcp"],
                "env": {"NB_API_KEY": api_key}
            }
        }
    }
    
    paths = []
    paths.append(_write_json(mcp_path, mcp_config, dry_run, force))
    
    # Cursor also supports .env for some extensions
    env_line = f"\nOPENAI_API_BASE={nb_url}/v1\nOPENAI_API_KEY={api_key}\n"
    if not dry_run:
        if env_path.exists():
            content = env_path.read_text()
            if "OPENAI_API_BASE" not in content:
                with open(env_path, "a") as f:
                    f.write(env_line)
        else:
            env_path.write_text(env_line)
    else:
        click.echo(f"[DRY-RUN] Would append to {env_path}")
    
    paths.append(env_path)
    return paths

def _setup_cline(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    settings_path = base / ".cline" / "settings.json"
    
    settings = {
        "apiConfig": {
            "provider": "openai",
            "openAiBaseUrl": f"{nb_url}/v1",
            "openAiApiKey": api_key,
            "openAiModelId": "gpt-4o"
        }
    }
    return [_write_json(settings_path, settings, dry_run, force)]

def _setup_github_copilot(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    # Custom instructions and VS Code settings
    base = Path.home() if global_dir else project_dir
    instr_path = base / ".github" / "copilot-instructions.md"
    vscode_path = base / ".vscode" / "settings.json"
    
    instr = f"This project uses NeuralBroker for local-first LLM routing. Endpoint: {nb_url}/v1"
    
    paths = []
    paths.append(_write_text(instr_path, instr, dry_run, force))
    
    vscode_settings = {
        "github.copilot.advanced": {
            "debug.overrideProxyUrl": nb_url,
            "debug.overrideCAPIUrl": nb_url
        }
    }
    # We should merge if exists, but for now simple write
    paths.append(_write_json(vscode_path, vscode_settings, dry_run, force))
    return paths

def _setup_gemini_cli(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    settings_path = base / ".gemini" / "settings.json"
    settings = {
        "api_base": f"{nb_url}/v1",
        "api_key": api_key
    }
    return [_write_json(settings_path, settings, dry_run, force)]

def _setup_opencode(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    config_path = base / "opencode.json"
    config = {
        "endpoint": f"{nb_url}/v1",
        "api_key": api_key
    }
    return [_write_json(config_path, config, dry_run, force)]

def _setup_warp(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    click.echo(f"\n{click.style('WARP SETUP:', fg='magenta', bold=True)}")
    click.echo(f"Run the following to set Warp's AI proxy:")
    click.echo(f"  export WARP_AI_PROXY={nb_url}/v1")
    
    base = Path.home()
    pref_path = base / ".warp" / "preferences.yaml"
    prefs = {"ai_proxy": f"{nb_url}/v1"}
    
    if dry_run:
        click.echo(f"[DRY-RUN] Would write to {pref_path}")
        return [pref_path]
    
    # Simple yaml write
    pref_path.parent.mkdir(parents=True, exist_ok=True)
    with open(pref_path, "w") as f:
        yaml.dump(prefs, f)
    return [pref_path]

def _setup_codex(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    env_path = project_dir / ".env"
    config_path = Path.home() / ".codex" / "config.json"
    
    env_line = f"\nCODEX_API_BASE={nb_url}/v1\nCODEX_API_KEY={api_key}\n"
    if not dry_run:
        with open(env_path, "a" if env_path.exists() else "w") as f:
            f.write(env_line)
    
    config = {"endpoint": f"{nb_url}/v1", "key": api_key}
    return [env_path, _write_json(config_path, config, dry_run, force)]

def _setup_amp(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    config_path = Path.home() / ".amp" / "config.json"
    config = {"url": f"{nb_url}/v1", "key": api_key}
    return [_write_json(config_path, config, dry_run, force)]

def _setup_kimi_code(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    config_path = base / ".kimi" / "config.json"
    env_path = project_dir / ".env"
    
    config = {"api_base": f"{nb_url}/v1", "api_key": api_key}
    env_line = f"\nKIMI_API_KEY={api_key}\n"
    if not dry_run:
        with open(env_path, "a" if env_path.exists() else "w") as f:
            f.write(env_line)
            
    return [_write_json(config_path, config, dry_run, force), env_path]

def _setup_firebender(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    config_path = base / ".firebender" / "config.json"
    config = {"endpoint": f"{nb_url}/v1", "token": api_key}
    return [_write_json(config_path, config, dry_run, force)]

def _setup_deep_agents(project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    base = Path.home() if global_dir else project_dir
    paths = []
    paths.append(_write_json(base / ".deepagent" / "config.json", {"url": nb_url}, dry_run, force))
    paths.append(_write_json(base / ".antigravity" / "config.json", {"backend": nb_url}, dry_run, force))
    return paths

# --- Phase 2 Setup ---

def _setup_skill_agent(slug: str, skill_path: str, env_var: str, extra_config_path: Optional[str], 
                       project_dir: Path, nb_url: str, api_key: str, dry_run: bool, force: bool) -> List[Path]:
    paths = []
    full_skill_path = project_dir / skill_path
    content = _skill_file_content(slug.replace("-", " ").title(), env_var)
    paths.append(_write_text(full_skill_path, content, dry_run, force))
    
    if extra_config_path:
        extra_path = project_dir / extra_config_path
        extra_config = {"neuralbroker": {"enabled": True, "url": nb_url}}
        paths.append(_write_json(extra_path, extra_config, dry_run, force))
        
    return paths

# Registry for agents that use the generic skill-file writer
PHASE_2_SPECS = [
    ("augment", ".augment/skills/neuralbroker.md", "AUGMENT_API_KEY", None),
    ("ibm-bob", ".bob/skills/neuralbroker.md", "BOB_API_KEY", None),
    ("openclaw", "skills/neuralbroker.md", "OPENCLAW_API_KEY", None),
    ("codebuddy", ".codebuddy/skills/neuralbroker.md", "CODEBUDDY_API_KEY", None),
    ("cortex-code", ".cortex/skills/neuralbroker.md", "CORTEX_API_KEY", None),
    ("kilo-code", ".kilocode/skills/neuralbroker.md", "KILO_API_KEY", None),
    ("kiro-cli", ".kiro/skills/neuralbroker.md", "KIRO_API_KEY", None),
    ("kode", ".kode/skills/neuralbroker.md", "KODE_API_KEY", None),
    ("qwen-code", ".qwen/skills/neuralbroker.md", "QWEN_API_KEY", None),
    ("trae", ".trae/skills/neuralbroker.md", "TRAE_API_KEY", None),
    ("windsurf", ".windsurf/skills/neuralbroker.md", "WINDSURF_API_KEY", ".windsurf/mcp_config.json"),
]

AGENT_REGISTRY: Dict[str, AgentIntegration] = {
    "claude-code": AgentIntegration("Claude Code", "claude-code", 1, [".claude/settings.json", "CLAUDE.md"], setup_fn=_setup_claude_code, launch_cmd="claude", launch_env_vars={"ANTHROPIC_BASE_URL": "{nb_url}/v1", "ANTHROPIC_API_KEY": "{api_key}", "CLAUDE_API_BASE": "{nb_url}/v1"}),
    "cursor": AgentIntegration("Cursor", "cursor", 1, [".cursor/mcp.json", ".env"], setup_fn=_setup_cursor, launch_cmd="cursor", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
    "cline": AgentIntegration("Cline", "cline", 1, [".cline/settings.json"], setup_fn=_setup_cline, launch_cmd="cline", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
    "github-copilot": AgentIntegration("GitHub Copilot", "github-copilot", 1, [".github/copilot-instructions.md", ".vscode/settings.json"], setup_fn=_setup_github_copilot, launch_cmd="code"),
    "gemini-cli": AgentIntegration("Gemini CLI", "gemini-cli", 1, [".gemini/settings.json"], setup_fn=_setup_gemini_cli, launch_cmd="gemini", launch_env_vars={"GOOGLE_API_BASE": "{nb_url}/v1", "GOOGLE_API_KEY": "{api_key}"}),
    "opencode": AgentIntegration("OpenCode", "opencode", 1, ["opencode.json"], setup_fn=_setup_opencode, launch_cmd="opencode", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
    "warp": AgentIntegration("Warp", "warp", 1, ["~/.warp/preferences.yaml"], setup_fn=_setup_warp, launch_cmd="warp", launch_env_vars={"WARP_AI_PROXY": "{nb_url}/v1"}),
    "codex": AgentIntegration("Codex", "codex", 1, [".env", "~/.codex/config.json"], setup_fn=_setup_codex, launch_cmd="codex", launch_env_vars={"CODEX_API_BASE": "{nb_url}/v1", "CODEX_API_KEY": "{api_key}"}),
    "amp": AgentIntegration("Amp", "amp", 1, ["~/.amp/config.json"], setup_fn=_setup_amp, launch_cmd="amp", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
    "kimi-code": AgentIntegration("Kimi Code", "kimi-code", 1, [".kimi/config.json", ".env"], setup_fn=_setup_kimi_code, launch_cmd="kimi", launch_env_vars={"KIMI_API_BASE": "{nb_url}/v1", "KIMI_API_KEY": "{api_key}"}),
    "firebender": AgentIntegration("Firebender", "firebender", 1, [".firebender/config.json"], setup_fn=_setup_firebender, launch_cmd="firebender", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
    "deep-agents": AgentIntegration("Deep Agents", "deep-agents", 1, [".deepagent/config.json", ".antigravity/config.json"], setup_fn=_setup_deep_agents, launch_cmd="deepagent", launch_env_vars={"OPENAI_API_BASE": "{nb_url}/v1", "OPENAI_API_KEY": "{api_key}"}),
}

# Add Phase 2 agents to registry
for slug, skill_path, env_var, extra in PHASE_2_SPECS:
    AGENT_REGISTRY[slug] = AgentIntegration(
        name=slug.replace("-", " ").title(),
        slug=slug,
        phase=2,
        config_paths=[skill_path] + ([extra] if extra else []),
        env_vars={env_var: "API key for the agent"},
        skill_path=skill_path,
        setup_fn=lambda pd, nu, ak, gd, dr, f, s=slug, sp=skill_path, ev=env_var, ex=extra: 
                 _setup_skill_agent(s, sp, ev, ex, pd, nu, ak, dr, f)
    )

PHASE_1_AGENTS = [slug for slug, a in AGENT_REGISTRY.items() if a.phase == 1]

# --- Public API ---

def setup(agent_slug: str, project_dir: Path, nb_url: str, api_key: str, global_dir: bool, dry_run: bool, force: bool) -> List[Path]:
    if agent_slug not in AGENT_REGISTRY:
        raise ValueError(f"Unknown agent: {agent_slug}")
    
    integration = AGENT_REGISTRY[agent_slug]
    if integration.setup_fn:
        return integration.setup_fn(project_dir, nb_url, api_key, global_dir, dry_run, force)
    return []

def list_agents() -> List[AgentIntegration]:
    return list(AGENT_REGISTRY.values())

def check_status(project_dir: Path) -> Dict[str, bool]:
    """Checks if each agent's primary config file exists."""
    status = {}
    for slug, integration in AGENT_REGISTRY.items():
        # Check primary path (first one)
        primary = integration.config_paths[0]
        if primary.startswith("~"):
            path = Path(primary).expanduser()
        else:
            path = project_dir / primary
        status[slug] = path.exists()
    return status

def remove_agent(agent_slug: str, project_dir: Path, global_dir: bool, dry_run: bool) -> List[Path]:
    if agent_slug not in AGENT_REGISTRY:
        raise ValueError(f"Unknown agent: {agent_slug}")
        
    integration = AGENT_REGISTRY[agent_slug]
    removed = []
    for rel_path in integration.config_paths:
        if rel_path.startswith("~"):
            path = Path(rel_path).expanduser()
        else:
            path = project_dir / rel_path
            
        if path.exists():
            if dry_run:
                click.echo(f"[DRY-RUN] Would remove {path}")
            else:
                path.unlink()
                removed.append(path)
    return removed

def get_installed_integrations(project_dir: Path) -> List[str]:
    """Returns a list of slugs for agents that appear to be installed."""
    status = check_status(project_dir)
    return [slug for slug, installed in status.items() if installed]
